### ISSUE TITLE
Generate a Quarkus project

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-project-initializer#26]
We want to make it easy to bootstrap a quarkus.io project. See https://twitter.com/brunoborges/status/1108182368064552960

**Comment by jeffmaury** [comment]
I'm dependent from the launcher catalog. Trying to see how can we add a Quarkus runtime to the catalog

**Comment by jeffmaury** [comment]
@fbricon is this still a requirement. I think this is covered by vscode-quarkus ?

**Comment by mohitsuman** [comment]
The OpenShift extension and VSCode Quarkus support the workflow. Hence closing this,
