### ISSUE TITLE
Improve release process to include sources when publishing vsix

### ISSUE THREAD

**Issue by nickboldt** [redhat-developer/vscode-project-initializer#40]
If https://download.jboss.org/jbosstools/adapters/stable/vscode-project-initializer/project_initializer-0.0.9-92.vsix is the latest stable release, then it should also include a source tarball so that downstream consumers who have this requirement (eg., Che and CodeReady Workspaces) can easily see the sources for the binary distribution.

OR... if you publish to GH under /releases/ you will get a tarball for free, such as 

* https://github.com/redhat-developer/vscode-project-initializer/archive/v0.0.8.tar.gz (exists)
* https://github.com/redhat-developer/vscode-project-initializer/archive/v0.0.9.tar.gz (doesn't exist)

Some existing examples of this:

* https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/
* https://github.com/redhat-developer/omnisharp-theia-plugin/releases/
* https://github.com/redhat-developer/vscode-openshift-tools/releases/

**Comment by nickboldt** [comment]
Reasons for this requirement can be seen in [CRW-441](https://issues.redhat.com/browse/CRW-441) and [CRW-491](https://issues.redhat.com/browse/CRW-491).

**Comment by nickboldt** [comment]
Ping! any progress here?

**Comment by jeffmaury** [comment]
No I was waiting for a PR :)

**Comment by nickboldt** [comment]
You could have said so 2 weeks ago

**Comment by nickboldt** [comment]
Any progress here? I don't see a vsix in https://github.com/redhat-developer/vscode-project-initializer/releases/tag/v0.0.9 or a source tarball in https://download.jboss.org/jbosstools/vscode/stable/vscode-project-initializer/ yet :(

**Comment by jeffmaury** [comment]
I thought waiting for next version would be ok for you, @nickboldt

**Comment by nickboldt** [comment]
Sure -- when is 0.0.10 due?

**Comment by jeffmaury** [comment]
Early January as I have not plan and you told me you don't need it before late January

**Comment by nickboldt** [comment]
> Early January as I have not plan and you told me you don't need it before late January

Reopening until a new release appears in https://download.jboss.org/jbosstools/vscode/stable/vscode-project-initializer/

**Comment by jeffmaury** [comment]
0.0.10 deployed
