### ISSUE TITLE
Issue: 404 Errors - Project Initializer by Red Hat - Visual Studio Marketplace

### ISSUE THREAD

**Issue by GrooveCS** [redhat-developer/vscode-project-initializer#48]
### Prerequisites

1.  [X] None

### Description

The Project Initializer by Red Hat on Visual Studio Marketplace has to 404's that need to be corrected. 

[ ![Project Initializer](https://qas-shared-assets.s3.amazonaws.com/snaps/i4v3m0jfrc) ](https://marketplace.visualstudio.com/items?itemName=redhat.project-initializer)

### Steps to Reproduce

1. Navigate to [Project Initializer by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.project-initializer)
2. Click on Right Sidebar > Resources > [License](https://marketplace.visualstudio.com/items/redhat.project-initializer/license)
3. Scroll down to Main Section > Extension Settings > Defaults to [https://forge.api.openshift.io/api/](https://forge.api.openshift.io/api/)

**Expected behavior:**

To browser to navigate to the resource. 

**Actual behavior:**

Get 404 Errors

**Reproduces how often:**

100% for the last several months

### Versions

Version: 0.0.10

### Additional Information

Let me know if you require any additional information.

**Comment by jeffmaury** [comment]
This is a REST endpoint prefix and not supposed to be used from a browser.
