### ISSUE TITLE
Question: Project Initializer Status - Last updated 2020-01-23

### ISSUE THREAD

**Issue by GrooveCS** [redhat-developer/vscode-project-initializer#49]
### Prerequisites

* [ x] Are you running the latest version?
* [ x] Are you reporting to the correct repository?

### Questions
1. Can the project be used with OpenShift 4.x? 
2. The project currently states the build as failing. What is the current ETA to address this issue?
3.  Does Project Initializer have any conflicts or challenges with other Visual Studio Extension? 

[ ![Project Initilizer](https://qas-shared-assets.s3.amazonaws.com/snaps/4vl7jv3vfa5) ](https://marketplace.visualstudio.com/items?itemName=redhat.project-initializer)

**Comment by jeffmaury** [comment]
This extension has no relation to OpenShift but generated projects can be deployed to OpenShift included 4.x
The build error is related to improper AppVeyor configuration, we'll tracking it
This extension has no known conflicts with other VSCode extensions
